# Generated by Django 5.0.7 on 2024-07-25 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_alter_workspace_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacemember',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace_team', to='workspaces.workspace'),
        ),
    ]
